### PR TITLE
Added Functor, Monoid, Foldable and Traversable to Cluster

### PR DESCRIPTION
**Pull request by jcristovao**
Sorry for another very small patch, but I think I'm finished by now :)

### CODE REVIEW

**Comment by alpmestan** [comment]
I think you need to add:

``` haskell
{-# LANGUAGE CPP #-}
-- this at the top of the file

#if !MIN_VERSION_base(4, 8, 0)
import Data.Foldable
import Data.Monoid
import Data.Traversable
#endif
-- this in the import section
```

To make your changes work on GHC 7.6 a nd 7.8. Do you mind adding that?

**Comment by jcristovao** [comment]
You're right, sorry about that.

It should be working now!

**Comment by alpmestan** [comment]
Thanks! Released a minute ago as `0.3.2`.

**Comment by jcristovao** [comment]
Thanks!

**Pull request merged**
